#!/usr/bin/env python3
"""CI 内でフルスタック（サイト生成物 ＋ Worker）を起動するための wrangler 設定を、本番の wrangler.toml から生成する。

手で複製した設定は必ずズレるので、正本（wrangler.toml）を読み、CI に必要な差分だけを上書きして wrangler.ci.json を書く。
差分（この 6 点のみ）:
  1. name        → reyz-contact-citest（本番 Worker と衝突させない）
  2. routes      → 削除（ローカル起動のみ。配備には使わない）
  3. assets      → サイト生成物のコピーを同じ origin から配信（html_handling=none: GitHub Pages と同じく /x.html をそのまま返す）
  4. vars        → ALLOWED_ORIGINS をローカルの origin に
  5. vars        → TURNSTILE_HOSTNAMES = example.com,127.0.0.1,localhost（公式テストキーの siteverify は hostname=example.com を返す）
  6. ratelimits  → 上限を 100 に（複数ケースを連続実行するため。429 自体は単体テストで担保）
使い方: python3 ci/make_ci_config.py --site <サイト生成物のコピー> --origin http://127.0.0.1:8787 --out wrangler.ci.jsonc
"""
import argparse, json, os, sys, tomllib

ap = argparse.ArgumentParser()
ap.add_argument('--src', default=os.path.join(os.path.dirname(__file__), '..', 'wrangler.toml'))
ap.add_argument('--site', required=True, help='静的サイト生成物のディレクトリ（コピー。テスト用サイトキーに差し替え済み）')
ap.add_argument('--origin', default='http://127.0.0.1:8787')
ap.add_argument('--out', default='wrangler.ci.jsonc')
a = ap.parse_args()

with open(a.src, 'rb') as f:
    cfg = tomllib.load(f)

cfg['name'] = 'reyz-contact-citest'
cfg['main'] = os.path.abspath(os.path.join(os.path.dirname(a.src), cfg['main']))   # 出力先が別ディレクトリでも本体を見つけられるよう絶対パスに
cfg.pop('routes', None)
cfg['workers_dev'] = False
cfg['assets'] = {'directory': os.path.abspath(a.site), 'html_handling': 'none'}
cfg.setdefault('vars', {})['ALLOWED_ORIGINS'] = a.origin
cfg['vars']['TURNSTILE_HOSTNAMES'] = 'example.com,127.0.0.1,localhost'
for rl in cfg.get('ratelimits', []):
    rl['simple']['limit'] = 100
with open(a.out, 'w', encoding='utf-8') as f:
    f.write('// GENERATED by ci/make_ci_config.py from wrangler.toml for CI only. Never deploy, never commit.\n')
    json.dump(cfg, f, ensure_ascii=False, indent=2)
print(f'wrote {a.out}: name={cfg["name"]} assets={cfg["assets"]["directory"]} origin={a.origin} ratelimit={[r["simple"] for r in cfg.get("ratelimits", [])]}', file=sys.stderr)
