const { chromium } = require('playwright'); const http = require('http'); const fs = require('fs'); const path = require('path');
const ROOT = process.argv[2], OUT = process.argv[3]; fs.mkdirSync(OUT, { recursive: true });
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png' };
const server = http.createServer((req, res) => { const u = decodeURIComponent(req.url.split('?')[0].split('#')[0]); const p = path.join(ROOT, u === '/' ? '/index.html' : u); if (!p.startsWith(ROOT) || !fs.existsSync(p) || fs.statSync(p).isDirectory()) { res.writeHead(404); return res.end(); } res.writeHead(200, { 'Content-Type': MIME[path.extname(p)] || 'application/octet-stream' }); fs.createReadStream(p).pipe(res); });
const PAGES = ['index.html', 'creator.html', 'creative.html', 'ai.html', 'contact.html', 'legal.html', 'works.html'];
let document_word = () => '?';
const marksFn = () => { const vh = innerHeight, maxS = Math.max(0, document.documentElement.scrollHeight - vh); const R = el => { const r = el.getBoundingClientRect(); return { y: r.top + scrollY, h: r.height }; }; const ks = Array.from(document.querySelectorAll('[data-word]')).map(el => { const r = R(el); const cp = el.parentElement.querySelector('.copy'); const st = cp ? R(el.parentElement) : r; return { word: el.dataset.word, kin: Math.min(Math.max(r.y + r.h / 2 - vh * 0.5, 0), maxS), kout: st.y + st.h - vh * 0.55, soff: r.y + r.h }; }); ks.sort((a, b) => a.kin - b.kin); for (let i = 0; i < ks.length; i++) { const k = ks[i], nx = ks[i + 1]; if (nx) { if (nx.kin <= k.kin) nx.kin = k.kin + 2; const lo = k.kin + vh * 0.12, hi = nx.kin - vh * 0.45; k.kout = lo <= hi ? Math.min(Math.max(k.kout, lo), hi) : (k.kin + nx.kin) / 2; } } return ks; };
const VPS = [{ n: 'd1440', w: 1440, h: 900 }, { n: 'm390', w: 390, h: 844, m: true }, { n: 'l1280x640', w: 1280, h: 640 }];
const litBBox = () => { const c = document.getElementById('field'); const d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data; const dpr = c.width / innerWidth; let minx = 1e9, maxx = -1, miny = 1e9, maxy = -1, n = 0; for (let i = 3; i < d.length; i += 4) if (d[i] > 40) { n++; const p = (i - 3) / 4, x = p % c.width, y = (p / c.width) | 0; if (x < minx) minx = x; if (x > maxx) maxx = x; if (y < miny) miny = y; if (y > maxy) maxy = y; } return n ? { x: minx / dpr, y: miny / dpr, w: (maxx - minx) / dpr, h: (maxy - miny) / dpr, lit: n } : null; };
const measure = (litFn, idx) => { const fn = eval('(' + litFn + ')'); const bb = fn(); if (!bb) return { lit: 0 }; const st = document.querySelectorAll('[data-word]')[idx].getBoundingClientRect(); const box = { x: st.left, y: st.top, w: st.width, h: st.height }; const inter = (a, b) => { const x = Math.max(a.x, b.x), y = Math.max(a.y, b.y), r = Math.min(a.x + a.w, b.x + b.w), btm = Math.min(a.y + a.h, b.y + b.h); return (r > x && btm > y) ? (r - x) * (btm - y) : 0; }; const area = bb.w * bb.h || 1; const texts = Array.from(document.querySelectorAll('main h1,main h2,main h3,main p,main dd,main dt,main .btn,main label,footer a,footer span')).filter(t => { const cp = t.closest('.copy'); return !cp || parseFloat(getComputedStyle(cp).opacity) >= 0.15; }).map(t => t.getBoundingClientRect()).filter(b => b.width > 0 && b.height > 0 && b.bottom > 0 && b.top < innerHeight); let to = 0; for (const t of texts) { const tr = { x: t.left, y: t.top, w: t.width, h: t.height }; const ia = inter(bb, tr); if (!ia) continue; const ix = Math.max(bb.x, tr.x), iy = Math.max(bb.y, tr.y), iw = Math.min(bb.x + bb.w, tr.x + tr.w) - ix, ih = Math.min(bb.y + bb.h, tr.y + tr.h) - iy; to += ia; } return { lit: bb.lit, inStage: +(inter(bb, box) / area).toFixed(2), textOverlap: +(to / area).toFixed(3), bbox: [Math.round(bb.x), Math.round(bb.y), Math.round(bb.w), Math.round(bb.h)], inView: +(inter(bb, { x: 0, y: 0, w: innerWidth, h: innerHeight }) / area).toFixed(2) }; };
(async () => {
  await new Promise(r => server.listen(0, '127.0.0.1', r)); const base = `http://127.0.0.1:${server.address().port}/`;
  const browser = await chromium.launch(); const out = { pages: {}, links: {} };
  const files = new Set(fs.readdirSync(ROOT).filter(f => f.endsWith('.html')));
  for (const pg of PAGES) { const html = fs.readFileSync(path.join(ROOT, pg), 'utf8'); const ids = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map(m => m[1])); const hrefs = [...html.matchAll(/href="([^"]+)"/g)].map(m => m[1]).filter(h => !/^(https?:|data:|mailto:|#$)/.test(h)); const bad = hrefs.filter(h => { const [f, a] = h.split('#'); if (f && !fs.existsSync(path.join(ROOT, f))) return true; if (!f && a && !ids.has(a)) return true; if (f && a && files.has(f)) { const other = fs.readFileSync(path.join(ROOT, f), 'utf8'); if (!new RegExp('\\sid="' + a + '"').test(other)) return true; } return false; }); out.links[pg] = { internal: hrefs.length, broken: [...new Set(bad)] }; }
  for (const pg of PAGES) {
    out.pages[pg] = {};
    for (const vp of VPS) {
      const ctx = await browser.newContext({ viewport: { width: vp.w, height: vp.h }, isMobile: !!vp.m, hasTouch: !!vp.m }); const page = await ctx.newPage();
      const r = { errors: [], console: [], failed: [] }; page.on('pageerror', e => r.errors.push(String(e))); page.on('console', m => { if (m.type() === 'error' && !/TUNNEL|fonts/.test(m.text())) r.console.push(m.text()); }); page.on('response', s => { if (s.status() >= 400 && !/fonts/.test(s.url())) r.failed.push(s.status() + ' ' + s.url()); });
      await page.addInitScript(() => { window.__ft = []; const o = window.requestAnimationFrame.bind(window); window.requestAnimationFrame = cb => o(ts => { const t0 = performance.now(); cb(ts); window.__ft.push(performance.now() - t0); }); });
      await page.goto(base + pg, { waitUntil: 'load' }); await page.waitForTimeout(1700);
      r.basics = await page.evaluate(() => ({ scrollW: document.documentElement.scrollWidth, innerW: innerWidth, h1: document.querySelectorAll('h1').length, current: Array.from(document.querySelectorAll('.nav a[aria-current="page"]')).map(a => a.getAttribute('href')), small: Array.from(document.querySelectorAll('a[href],button,input,select,textarea')).filter(el => { const cs = getComputedStyle(el); if (cs.display === 'none' || el.closest('[hidden]')) return false; const b = el.getBoundingClientRect(); return b.width > 0 && (b.height < 44 || b.width < 44); }).map(el => (el.textContent.trim().slice(0, 12) + ' ' + Math.round(el.getBoundingClientRect().width) + 'x' + Math.round(el.getBoundingClientRect().height))) }));
      if (vp.n !== 'l1280x640') await page.screenshot({ path: path.join(OUT, `${pg.replace('.html', '')}_${vp.n}_rest.png`) });
      // chapters: scroll each [data-word] chapter to the viewport centre and measure the shape
      r.chapters = [];
      const n = await page.evaluate(() => document.querySelectorAll('[data-word]').length); const wordsList = await page.evaluate(() => Array.from(document.querySelectorAll('[data-word]')).map(e => e.dataset.word)); document_word = i => wordsList[i];
      for (let i = 0; i < n; i++) {
        await page.evaluate(([i, mf]) => { const ks = eval('(' + mf + ')')(); window.scrollTo({ top: ks[i].kin, behavior: 'instant' }); }, [i, marksFn.toString()]); await page.waitForTimeout(1500);
        const mm = await page.evaluate(([litFn, mFn, i]) => { const f = eval('(' + mFn + ')'); const res = f(litFn, i); const el = document.querySelectorAll('[data-word]')[i]; res.word = el.dataset.word; const cp = el.parentElement.querySelector('.copy'); res.copyOpacity = cp ? +getComputedStyle(cp).opacity : null; return res; }, [litBBox.toString(), measure.toString(), i]);
        r.chapters.push(mm);
        if (vp.n !== 'l1280x640') await page.screenshot({ path: path.join(OUT, `${pg.replace('.html', '')}_${vp.n}_${i}_${mm.word}.png`) });
        if (i < n - 1) { // hold probe: just before the dissolve mark the word is still formed and its copy fully visible
          await page.evaluate(([i, mf]) => { const ks = eval('(' + mf + ')')(); window.scrollTo({ top: Math.max(0, ks[i].kout - 1), behavior: 'instant' }); }, [i, marksFn.toString()]); await page.waitForTimeout(1500);
          const hold = await page.evaluate(([litFn, mFn, i]) => { const f = eval('(' + mFn + ')'); const res = f(litFn, i); const el = document.querySelectorAll('[data-word]')[i]; const cp = el.parentElement.querySelector('.copy'); const slot = el.getBoundingClientRect(); return { inStage: res.inStage, copyOpacity: cp ? +getComputedStyle(cp).opacity : null, slotInView: (slot.top + slot.bottom) / 2 > 0 && (slot.top + slot.bottom) / 2 < innerHeight, bbox: res.bbox }; }, [litBBox.toString(), measure.toString(), i]);
          r.chapters.push({ word: 'hold:' + document_word(i), ...hold });
        }
        if (i < n - 1) { // midpoint: the cloud travels as a thread — must be in view and off the text
          await page.evaluate(([i, mf]) => { const ks = eval('(' + mf + ')')(); const A = ks[i], B = ks[i + 1]; const y = B.word === 'loop' ? B.kin - innerHeight * 0.45 : (A.kout + B.kin) / 2; window.scrollTo({ top: Math.max(0, y), behavior: 'instant' }); }, [i, marksFn.toString()]); await page.waitForTimeout(1500);
          const mt = await page.evaluate(([litFn, mFn, i]) => { const f = eval('(' + mFn + ')'); const res = f(litFn, i); const cps = [i, i + 1].map(j => { const cp = document.querySelectorAll('[data-word]')[j].parentElement.querySelector('.copy'); return cp ? +getComputedStyle(cp).opacity : null; }); return { textOverlap: res.textOverlap, inView: res.inView, bbox: res.bbox, lit: res.lit, copyOpacities: cps }; }, [litBBox.toString(), measure.toString(), i]);
          r.chapters.push({ word: 'thread→' + document_word(i + 1), ...mt });
        }
      }
      await page.evaluate(() => window.scrollTo({ top: document.documentElement.scrollHeight, behavior: 'instant' })); await page.waitForTimeout(1500);
      r.end = await page.evaluate(([litFn]) => { const fn = eval('(' + litFn + ')'); const bb = fn(); const fs = document.querySelector('.foot-slot').getBoundingClientRect(); const inter = (a, b) => { const x = Math.max(a.x, b.x), y = Math.max(a.y, b.y), r = Math.min(a.x + a.w, b.x + b.w), btm = Math.min(a.y + a.h, b.y + b.h); return (r > x && btm > y) ? (r - x) * (btm - y) : 0; }; return { loopInSlot: bb ? +(inter(bb, { x: fs.left, y: fs.top, w: fs.width, h: fs.height }) / (bb.w * bb.h)).toFixed(2) : 0 }; }, [litBBox.toString()]);
      if (vp.n !== 'l1280x640') await page.screenshot({ path: path.join(OUT, `${pg.replace('.html', '')}_${vp.n}_end.png`) });
      r.frame = await page.evaluate(() => { const t = window.__ft.slice(30); const s = [...t].sort((a, b) => a - b); return { avg: +(t.reduce((a, c) => a + c, 0) / t.length).toFixed(2), p95: +s[Math.floor(s.length * 0.95)].toFixed(2) }; });
      out.pages[pg][vp.n] = r; await ctx.close();
    }
  }
  await browser.close(); server.close(); fs.writeFileSync(path.join(OUT, 'report.json'), JSON.stringify(out, null, 2)); console.log('done');
})().catch(e => { console.error('FATAL', e); process.exit(1); });
